spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8088"

#  datasource:
#    url: jdbc:mysql://localhost:3306/hcUser
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: gangan123
#
#  jpa:
#    properties:
#      hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ganganbipin@gmail.com
    password: aorszepckroufsbf
    port: '587'