spring:
  application:
    name: api-service
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - path=/user/**
            filters:
              -name: JwtRequestFilter
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - path=/auth/**
            filters:
              -name: JwtRequestFilter

#  datasource:
#    url: jdbc:mysql://localhost:3306/hcUser
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: gangan123

#  jpa:
#    properties:
#      hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
